### ISSUE TITLE
Growl plugin doesn't see running instances

### ISSUE THREAD

**Issue by stevelucky** [OctoPrint/OctoPrint-Growl#3] opened 2015-05-12 18:55 UTC
I'm running growl on my Mac (have been for years). I've got the plugin installed in OctoPrint along with discovery and pybonjour but for some reason, I still can't see the running instance in the OctoPrint Growl settings. Am I missing something?

**Comment by foosel** [comment] 2015-05-12 19:27
Not really, but I have to say I also noticed that especially the discovery of the growl instances appears to be a moody beast. Sometimes it works for me, sometimes it doesn't. I haven't yet figured out what happens there, but it appears that the discovery request within pybonjour just runs into a timeout of some kind and nothinger gets return. It's a real mystery.

**Comment by stevelucky** [comment] 2015-05-12 19:29
Yeah, it's weird. My instance on my iMac finally showed up, out of nowhere, but test notifications still time out.

**Comment by foosel** [comment] 2015-05-12 19:33
This may sound odd, but "good to know", because I was wondering if that was an issue caused by my somewhat odd Windows setup here or not.

Also had the timeouts happen occasionally. It usually recovered after a restart though. I promise to take another look at that when I have finally pushed 1.2.0 out of the door (unless someone else does).

**Comment by stevelucky** [comment] 2015-05-12 19:34
A restart of OctoPrint or of the Growl host?

**Comment by foosel** [comment] 2015-05-12 19:34
OctoPrint, sorry, should have been clearer.

**Comment by stevelucky** [comment] 2015-05-12 23:04
FWIW, it seems as if it's just the test notification that times out. All my other OctoPrint Growl notifications seem to be working just fine.

**Comment by foosel** [comment] 2020-07-01 13:31
I'm closing this as I have no time to maintain this and my call for adoption of this plugin has also gone unanswered for close to two years now.

**Closed by foosel** 2020-07-01 13:31 UTC
